# Generated by Django 3.2 on 2021-07-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('alamat', models.TextField(null=True)),
                ('usia', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_buku', models.CharField(max_length=200, null=True)),
                ('penulis', models.CharField(max_length=200, null=True)),
                ('penerbit', models.CharField(max_length=200, null=True)),
                ('tahun', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_pinjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('anggota_key', models.ManyToManyField(to='buku.anggota')),
                ('buku_key', models.ManyToManyField(to='buku.buku')),
            ],
        ),
    ]
