# Generated by Django 3.2 on 2021-07-22 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_pinjaman',
            name='anggota_key',
        ),
        migrations.AddField(
            model_name='data_pinjaman',
            name='anggota_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buku.anggota'),
        ),
        migrations.RemoveField(
            model_name='data_pinjaman',
            name='buku_key',
        ),
        migrations.AddField(
            model_name='data_pinjaman',
            name='buku_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buku.buku'),
        ),
    ]
