# Generated by Django 3.0 on 2021-07-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_auto_20210722_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anggota',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buku',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='data_pinjaman',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='data_pinjaman',
            name='tanggal_kembali',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data_pinjaman',
            name='tanggal_pinjam',
            field=models.DateField(blank=True, null=True),
        ),
    ]
